Repository CloudProjectD/back-end, pull requests merged in 2023-11, with the labels that each got.

#10 [Fix] rearrange relationship & add like into base
  app/db/base.py
  app/models/schemas/likes.py
  app/models/schemas/posts.py
  app/models/schemas/users.py
Labels: bug

#16 [Refactor] change image file path
  app/api/routes/frees.py
  app/api/routes/rooms.py
  app/crud/crud_frees.py
  app/crud/crud_posts.py
  app/crud/crud_rooms.py
  app/models/schemas/likes.py
  app/models/schemas/posts.py
  app/services/aws.py
Labels: refactor

#21 [Feat] get market one
  app/api/routes/markets.py
  app/core/config.py
  app/crud/crud_markets.py
  app/crud/crud_posts.py
  app/models/domain/markets.py
  app/services/aws.py
Labels: enhancement, refactor

#23 [Feat] get market data all
  app/api/routes/markets.py
  app/crud/crud_posts.py
Labels: enhancement

#25 [Feat] update market
  app/api/routes/markets.py
  app/crud/crud_markets.py
  app/crud/crud_posts.py
  app/models/domain/markets.py
  app/models/domain/posts.py
Labels: enhancement

#27 [Feat] delete market data
  app/api/routes/markets.py
  app/crud/crud_markets.py
  app/crud/crud_posts.py
Labels: enhancement

#29 [Feat] Get messages by current user
  app/api/routes/api.py
  app/api/routes/messages.py
  app/crud/crud_likes.py
  app/models/domain/messages.py
  app/services/aws.py
  app/services/google.py
Labels: bug, enhancement
